name: 'Connect to GKE'
description: 'Connect runner to a Google Kubernetes Engine cluster on the Google Cloud Platform'
branding:
  icon: 'anchor'  
  color: 'gray-dark'
inputs:
  GCP_SA_KEY:
    description: 'Service Account Key JSON (see: https://github.com/google-github-actions/auth)'
    required: true
  GCP_PROJECT_ID:
    description: 'GCP Project ID (see: https://github.com/google-github-actions/setup-gcloud)'
    required: true
  GKE_CLUSTER:
    description: 'GKE cluster to be connected to (check in GCP console, under Kubernetes Engine to get the cluster name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate at GCP
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ inputs.GCP_SA_KEY }}'

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v0
      with:   
        project_id: ${{ inputs.GCP_PROJECT_ID }}
    
    - name: Get GKE credentials
      shell: bash
      run: gcloud container clusters get-credentials "${{ inputs.GKE_CLUSTER }}"
