name: test

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    env:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Connect to GKE
        uses: ./
        with:
          GCP_SA_KEY: '${{ secrets.GCP_SA_KEY }}'
          GCP_PROJECT_ID: '$GCP_PROJECT_ID'
          GKE_CLUSTER: '$GKE_CLUSTER'